spring.application.name=iot-cat-tracker
spring.datasource.url=jdbc:postgresql://localhost:5432/iot_cat_tracker_db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.datasource.driver-class-name=org.postgresql.Driver

spring.data.mongodb.uri=mongodb://mongodb:mongodb@localhost:27017/raspberrypi_db

pir.flask.api.url=${PIR_FLASK_API_URL}
backend.url=${BACKEND_URL}
mailgun.api.key=${MAILGUN_API_KEY}
mailgun.domain=${MAILGUN_DOMAIN}
mailgun.sender.email=${MAILGUN_SENDER_EMAIL}
mailgun.recipient.email=${MAILGUN_RECIPIENT_EMAIL}
task.interval=60000

logging.file.name=logs/application.log

logging.level.root=INFO